feat(limits): apply limits to cpu for pythonrunner and deployments if…
DataCater/datacater pull request #111
Opened 2022-12-23 14:29 UTC by HknLof

… provided

2022-12-23 16:42 UTC, flippingbits requested changes
Thanks for this PR! :) I left a few comments.

2022-12-23 16:42 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/kubernetes/DataCaterK8sConfig.java
> +          .getOptionalValue("datacater.pythonrunner.resources.requests.memory", String.class)
Should be `datacater.pythonrunner.resources.limits.memory`.

2022-12-23 16:42 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/kubernetes/DataCaterK8sConfig.java
> +                s ->
Can you please rename `s` to something meaningful?

2022-12-23 16:42 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/kubernetes/DataCaterK8sConfig.java
> +          .orElse("0.5");
`0.5` does not make sense as a default value for the memory limit. This sounds more like it was meant for CPU.

2022-12-23 16:42 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/kubernetes/DataCaterK8sConfig.java
> +          .orElse("200Mi");
`200Mi` feels too much. In my Minikube cluster, I observed a memory usage of ~ `95Mi` when not using any requests/limits.

2022-12-23 16:44 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/kubernetes/DataCaterK8sConfig.java
> +          .orElse("0.5");
Might just use the same default as for the request to follow the best practice of setting memory request=memory limit?

2023-01-03 10:30 UTC, HknLof commented
@flippingbits Could you check again, I updated the blocks accordingly. Introduced `100Mi` for memory limit and request.

2023-01-03 10:47 UTC, flippingbits approved these changes
LGTM, thanks for the iteration

2023-01-03 12:39 UTC, merged