Feat: k8 manifests and helm updates
DataCater/datacater pull request #142
Opened 2023-01-13 12:59 UTC by ChrisRousey

Added python statefulset execution to k8 manifests
added flag to helmchart to remove helm-specific labels

2023-01-13 14:41 UTC, flippingbits requested changes
Thanks! Left a couple of comments :)

2023-01-13 14:41 UTC, flippingbits commented on k8s-manifests/minikube-any-namespace.yaml
> +            failureThreshold: 3
We need to bump the failureThreshold to `10`, the Python Runner typically takes a couple of seconds to start.

2023-01-13 14:41 UTC, flippingbits commented on k8s-manifests/minikube-any-namespace.yaml
> +            failureThreshold: 3
We might want to adjust the failureTreshold to `10` as well here, similar to the readinessProbe.

2023-01-13 14:41 UTC, flippingbits commented on k8s-manifests/minikube-with-postgres-ns-default.yaml
> +              value: datacater
We should keep `default` here.

2023-01-13 14:41 UTC, flippingbits commented on k8s-manifests/minikube-with-postgres-ns-default.yaml
> +            failureThreshold: 3
Please bump it to `10`.

2023-01-13 14:41 UTC, flippingbits commented on k8s-manifests/minikube-with-postgres-ns-default.yaml
> +            failureThreshold: 3
Please bump it to `10`.

2023-01-15 11:59 UTC, HknLof approved these changes

2023-01-15 12:25 UTC, flippingbits approved these changes

2023-01-15 12:25 UTC, merged