feature: Make deployment replicas configurable on resource level
DataCater/datacater pull request #178
Opened 2023-03-03 10:30 UTC by ChrisRousey

This PR is to make the deployment replica amount configurable at the resource level, when creating a new deployment.
Ticket reference: #112

2023-03-13 13:44 UTC, ChrisRousey commented
The changes of this PR are documentated in a [gitbook PR](https://app.gitbook.com/o/v6uGZYtfBxqXSwxx4vXu/s/FLAe5WA2FuJRguGU5lqo/~/changes/68/docs/api/deployments)

2023-03-13 13:54 UTC, flippingbits requested changes
Thanks for the great work :) I left two questions/remarks.

2023-03-13 13:54 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
> +            "%s://%s.%s.%s.svc.cluster.local:%d%s", protocol, ip, service, namespace, port, path);
I feel that we could get rid of the service here. From my understanding, we could [directly access the replica via its pod IP](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods).

2023-03-13 13:54 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java
> +    if (replicaPosition > 0) {
We should also take care of the case where `replicaPosition <= 0`.

2023-03-13 13:54 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java
> +    Pod first;
I feel that we could improve the naming here.

2023-03-14 16:14 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
> +            "%s://%s.%s.%s.svc.cluster.local:%d%s", protocol, ip, service, namespace, port, path);
I think that we no longer need it given that we are directly working with pods. What do you think?

2023-03-22 10:20 UTC, ChrisRousey commented
This PR is ready for review @flippingbits @HknLof @olis1996 

I had to remove two tests regarding the logs, since the kubernetes mockserver doesn't actually seem to create real deployments/replicas under the hood. I have created an issue #193 to address this.

2023-03-22 10:32 UTC, flippingbits commented on platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java
> +            .orElse("nightly");
[For other image versions](https://github.com/DataCater/datacater/blob/main/platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java#L95), we point to the latest stable release. Shall we do the same here?

2023-03-22 10:48 UTC, flippingbits approved these changes
💯

2023-03-22 14:05 UTC, merged